# Generated by Django 4.2 on 2023-04-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_remove_trait_traits'),
        ('pets', '0004_alter_pet_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='trait',
            field=models.ManyToManyField(related_name='traits', to='traits.trait'),
        ),
    ]
