# Generated by Django 4.2 on 2023-04-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_remove_pet_trait'),
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trait',
            name='traits',
            field=models.ManyToManyField(related_name='traits', to='pets.pet'),
        ),
    ]
