# Generated by Django 4.2 on 2023-04-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_trait_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='traits',
        ),
    ]
